@AmarivAPI_HostAddress = http://localhost:5100

GET {{AmarivAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{AmarivAPI_HostAddress}}/RecuperaMaterial
Content-Type: application/json
Accept: application/json

{
   "id": "1"
}

###

POST {{AmarivAPI_HostAddress}}/signin
Content-Type: application/json
Accept: application/json

{
   "Nome": "Mike",
   "Email": "mike@email.com",
   "Password": "Test@123",
   "RePassword": "Test@123"
}

###

POST {{AmarivAPI_HostAddress}}/SalvarMaterial
Content-Type: application/json
Accept: application/json

{
   "Descricao": "Ferro",
   "Tipo": "Metal",
   "Peso": "Pesado"
}

###
POST {{AmarivAPI_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
  "Email": "mike@email.com",
  "Password": "Test@123"
}

###

POST {{AmarivAPI_HostAddress}}/api/notificacao
Content-Type: application/json
Accept: application/json

{
   "UserId": "30ad6015-d6c6-495f-a57c-d205267d77c9",
   "Titulo": "ff22fft",
   "Corpo": "fffftification."
}

###

GET {{AmarivAPI_HostAddress}}/api/notificacao?userId=30ad6015-d6c6-495f-a57c-d205267d77c9
Accept: application/json

###

PUT {{AmarivAPI_HostAddress}}/api/notificacao/2
Content-Type: application/json
Accept: application/json

{
   "Titulo": "3 Notification",
   "Corpo": "This notification has been updated."
}

###
DELETE {{AmarivAPI_HostAddress}}/api/notificacao/2
Accept: application/json