@AmarivAPI_HostAddress = http://localhost:5100

GET {{AmarivAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{AmarivAPI_HostAddress}}/RecuperaMaterial?id=2
Accept: application/json

###

GET {{AmarivAPI_HostAddress}}/RecuperaMateriais
Accept: application/json

###

POST {{AmarivAPI_HostAddress}}/SalvarMaterial
Content-Type: application/json
Accept: application/json

{
   "Descricao": "Ferro",
   "Tipo": "Metal",
   "Peso": "Pesado"
}

###

POST {{AmarivAPI_HostAddress}}/UpdateMaterial?id=1
Content-Type: application/json
Accept: application/json

{
   "Descricao": "Aço",
   "Tipo": "Metal",
   "Peso": "Médio"
}

###

DELETE {{AmarivAPI_HostAddress}}/DeletarMaterial?id=2
Accept: application/json

###

POST {{AmarivAPI_HostAddress}}/signin
Content-Type: application/json
Accept: application/json

{
   "Nome": "Mike",
   "Email": "mike@email.com",
   "Password": "Test@123",
   "RePassword": "Test@123"
}

###

POST {{AmarivAPI_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
  "Email": "mike@email.com",
  "Password": "Test@123"
}

###

POST {{AmarivAPI_HostAddress}}/api/notificacao
Content-Type: application/json
Accept: application/json

{
   "UserId": "30ad6015-d6c6-495f-a57c-d205267d77c9",
   "Titulo": "ff22fft",
   "Corpo": "fffftification."
}

###

GET {{AmarivAPI_HostAddress}}/api/notificacao?userId=30ad6015-d6c6-495f-a57c-d205267d77c9
Accept: application/json

###

PUT {{AmarivAPI_HostAddress}}/api/notificacao/2
Content-Type: application/json
Accept: application/json

{
   "Titulo": "3 Notification",
   "Corpo": "This notification has been updated."
}

###

DELETE {{AmarivAPI_HostAddress}}/api/notificacao/2
Accept: application/json


###
GET {{AmarivAPI_HostAddress}}/api/funcionario
Accept: application/json



###
GET {{AmarivAPI_HostAddress}}/api/funcionario/1
Accept: application/json



###
POST {{AmarivAPI_HostAddress}}/api/funcionario
Content-Type: application/json
Accept: application/json

{
    "Nome": "Maria Souza",
    "Matricula": "789012",
    "Email": "marssffia.soufffsszas@example.com",
    "Cpf": "98765432109",
    "Sexo": "Feminino",
    "DataAdmissao": "2023-04-15",
    "DataNascimento": "1995-08-20",
    "Telefone": "11987654321",
    "Cargo": "Analista",
    "Senha": "SenhaSegura123",
    "SuportaPeso": true
}

###
PUT {{AmarivAPI_HostAddress}}/api/funcionario/1
Content-Type: application/json
Accept: application/json

{
    "Nome": "Mariaaaa Souza Atualizada",
    "Matricula": "789012",
    "Email": "maria.souza@example.com",
    "Cpf": "98765432109",
    "Sexo": "Feminino",
    "DataAdmissao": "2023-04-15",
    "DataNascimento": "1995-08-20",
    "Telefone": "11987654321",
    "Cargo": "Analista Sênior",
    "Senha": "NovaSenha123",
    "SuportaPeso": true
}


###
DELETE {{AmarivAPI_HostAddress}}/api/funcionario/1
Accept: application/json