@AmarivAPI_HostAddress = http://localhost:5100

GET {{AmarivAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{AmarivAPI_HostAddress}}/RecuperaMaterial
Content-Type: application/json
Accept: application/json

{
   "id": "1"
}

###

POST {{AmarivAPI_HostAddress}}/signin
Content-Type: application/json
Accept: application/json

{
   "Nome": "John",
   "Email": "john@email.com",
   "Password": "@Test123",
   "RePassword": "@Test123"
}

###

POST {{AmarivAPI_HostAddress}}/Emp/GetGatheringItinerary
Content-Type: application/json
Accept: application/json

{
   "Descricao": "Ferro",
   "Tipo": "Metal",
   "Peso": "Pesado"
}

###
POST {{AmarivAPI_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
  "Email": "john@email.com",
  "Password": "@Test123"
}

###